name: Slack Webhook

on:
  pull_request:
    branches:
      - main
      - development
  push:
    branches:
      - main
      - development

jobs:
  new_pull_request:
    runs-on: ubuntu-latest
    name: New Pull Request to Repo
    steps:
      - name: Notify Slack on Success
        if: success()
        id: slack-success
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "text": "${{ job.status }}! PR 올렸으니 comment 부탁드려요!\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}",
              "attachments": [
                {
                  "color": "#36a64f",
                  "title": "${{ github.repository }}", 
                  "title_link": "https://github.com/${{github.repository}}",
                  "fields": [
                    {
                      "title": "Repository",
                      "value": "${{ github.repository }}",
                      "short": true
                    },
                    {
                      "title": "Tag",
                      "value": "${{ github.ref_name }}",
                      "short": true
                    }
                  ]      
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK

      - name: Notify Slack on Failure
        if: failure()
        id: slack-failure
        uses: slackapi/slack-github-action@v1.24.0
        with:
          channel-id: "C061FPGQ6E6"
          payload: |
            {
              "attachments": [
                {
                  "color": "#ff0000", 
                  "title": "${{ github.repository }}",
                  "title_link": "https://github.com/${{github.repository}}", 
                  "text": "GitHub Action 실패 :x:",
                  "fields": [
                    {
                      "title": "Repository",
                      "value": "${{ github.repository }}",
                      "short": true
                    },
                    {
                      "title": "Tag",
                      "value": "${{ github.ref_name }}",
                      "short": true
                    }
                  ]      
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
